# The primary user `lvdar`. den's batteries replace the hand-rolled user record
# in modules/nixos/user.nix: define-user (the account + HM home dir),
# primary-user (wheel/networkmanager), user-shell (zsh at OS + home).
# Extra groups (video/cdrom/media/…) will arrive via the extraGroups quirk as
# features are converted; the home baseline is added under `homeManager`.
{den, ...}: {
  den.aspects.lvdar = {
    includes = [
      den.batteries.define-user
      den.batteries.primary-user
      (den.batteries.user-shell "zsh")
      den.aspects.roles.home-base
    ];

    homeManager = {
      osConfig,
      lib,
      ...
    }: {
      # The default is just this host's own key, which is ed25519 — and the
      # iDRAC runs OpenSSH 6.6 and offers only ssh-rsa, ssh-dss and
      # ecdsa-sha2-nistp256, so it cannot parse one. Hence a second, RSA
      # identity used for that one destination.
      #
      # 2048 rather than 4096: Dell KB 000142481 records that iDRAC 7/8
      # rejects a 4096-bit RSA key generated by OpenSSH 6.6 or later, which
      # is every OpenSSH anyone still runs. The alternative is keeping an
      # ancient keygen around to make one.
      #
      # Named for what it is for rather than for a host, unlike the others:
      # every existing key identifies a machine, this identifies a purpose.
      cosmos.cli.programs.ssh.identities = [osConfig.networking.hostName "idrac"];

      # `ssh idrac` reaches the BMC through pioneer. Deliberately a jump
      # rather than another proxy: services/idrac.nix forwards HTTPS only, and
      # the BMC's sshd has no business being reachable from anywhere except
      # the host already standing in front of it.
      programs.ssh.settings."idrac" = lib.hm.dag.entryBefore ["*"] {
        HostName = "192.168.2.111";
        ProxyJump = "pioneer";

        # No User on purpose. The BMC account has the same name as the local
        # one, so ssh's default — the local username — is already right, and
        # naming it here would only be a second place to keep in step. The
        # servers need theirs set because their account is `nixos`; this does
        # not.
        IdentityFile = "~/.ssh/id_idrac";
        IdentitiesOnly = true;

        # OpenSSH 6.6 on the BMC predates rsa-sha2 (7.2), so it can only sign
        # with SHA-1 ssh-rsa, which every current client disables by default.
        # Without these the key is never offered and it looks like the BMC
        # rejected it.
        PubkeyAcceptedAlgorithms = "+ssh-rsa";
        HostKeyAlgorithms = "+ssh-rsa";

        # OpenSSH 10 warns on every connection that the key exchange is not
        # post-quantum. It is right and it will never stop being right: this
        # BMC's OpenSSH 6.6 predates the idea by a decade and no firmware is
        # coming. `no-pq-kex` silences that one warning and leaves the rest of
        # the weak-crypto warnings in place, which matters — the whole reason
        # this host needs special handling is that its crypto is old, and
        # blanket `no` would hide the next surprise too.
        WarnWeakCrypto = "no-pq-kex";

        # Two hops of handshake — through pioneer, then a 2015 BMC doing RSA
        # on an embedded CPU — for every `ssh idrac racadm ...`. Reusing one
        # connection makes the second and later commands close to instant.
        # The global block turns multiplexing off; this turns it back on for
        # the one host where it is worth it, reusing the ControlPath already
        # defined there.
        ControlMaster = "auto";
        ControlPersist = "10m";
      };
    };
  };
}
