# The primary user `lvdar`, built from den batteries (define-user,
# primary-user, user-shell).
{den, ...}: {
  den.aspects.lvdar = {
    includes = [
      den.batteries.define-user
      den.batteries.primary-user
      (den.batteries.user-shell "zsh")
      den.aspects.roles.home-base
    ];

    homeManager = {
      osConfig,
      lib,
      ...
    }: {
      # The default identity is this host's ed25519 key, which iDRAC's
      # OpenSSH 6.6 cannot parse — hence a second, RSA identity for that one
      # destination. 2048 bits: Dell KB 000142481 — iDRAC 7/8 rejects
      # 4096-bit RSA keys generated by OpenSSH 6.6+.
      cosmos.cli.programs.ssh.identities = [osConfig.networking.hostName "idrac"];

      # `ssh idrac` reaches the BMC through pioneer. A jump, not another
      # proxy: the BMC's sshd has no business being reachable from anywhere
      # except the host in front of it (services/idrac.nix forwards HTTPS only).
      programs.ssh.settings."idrac" = lib.hm.dag.entryBefore ["*"] {
        HostName = "192.168.2.111";
        ProxyJump = "pioneer";

        # No User on purpose: the BMC account shares the local username, so
        # ssh's default is already right (servers need theirs — they are `nixos`).
        IdentityFile = "~/.ssh/id_idrac";
        IdentitiesOnly = true;

        # BMC OpenSSH 6.6 predates rsa-sha2 (7.2); it can only sign SHA-1
        # ssh-rsa, disabled by default in current clients — without these the
        # key is never offered.
        PubkeyAcceptedAlgorithms = "+ssh-rsa";
        HostKeyAlgorithms = "+ssh-rsa";

        # OpenSSH 10's post-quantum KEX warning is correct and permanent (6.6
        # predates PQ; no firmware coming). `no-pq-kex` silences only that
        # warning — blanket `no` would hide the next weak-crypto surprise too.
        WarnWeakCrypto = "no-pq-kex";

        # Two handshake hops (pioneer, then a slow 2015 BMC) per command;
        # reuse one connection. Global block disables multiplexing; re-enable
        # it just here, reusing the global ControlPath.
        ControlMaster = "auto";
        ControlPersist = "10m";
      };
    };
  };
}
