# services.taskchampion — the sync server Taskwarrior 3 replicates against.
#
# Taskwarrior 3 dropped the old taskd/taskserver entirely; the replacement is
# TaskChampion, and this is its server half. It is not a task database. Every
# client holds a complete replica and syncs an encrypted operation log through
# here, which has two consequences worth knowing before trusting it with
# anything:
#
#   * The server cannot read the tasks. The client encrypts with
#     `sync.encryption_secret`, which never leaves the client — so that secret,
#     not this host, is what stands between a copy of this directory and your
#     task list. Lose it on every client and the history here is unreadable.
#   * Losing this directory is not losing the tasks. Any surviving replica can
#     re-initialise sync and repopulate it. That is why the backup entry in
#     hosts/endeavour.nix calls it convenience rather than survival.
#
# Mesh-only, and deliberately not published through gaia. The only
# authentication TaskChampion has is knowing a client-id UUID; the encryption
# is what protects the contents, but an unauthenticated writer who guessed or
# saw an id could still append junk to that client's history. On the mesh the
# NetBird ACL is the real gate, and every device that runs Taskwarrior is
# already on it — including voyager when it is away from the house.
{...}: {
  den.aspects.services.taskchampion.nixos = {
    config,
    lib,
    ...
  }: let
    inherit (lib.options) mkOption;
    inherit (lib.types) listOf port str;

    cfg = config.cosmos.services.taskchampion;
  in {
    options.cosmos.services.taskchampion = {
      port = mkOption {
        type = port;
        default = 10222;
        description = ''
          Upstream's own default. Mesh-only, so it is opened on the netbird
          interface in hosts/endeavour.nix and appears nowhere in gaia.nix.
        '';
      };

      allowedClientIds = mkOption {
        type = listOf str;
        default = [];
        example = ["3f5e0a2c-1b7d-4c9e-8a11-0d6f2b4c8e90"];
        description = ''
          Client-id UUIDs the server will accept, or every id if empty.

          Empty is the honest default: the id is generated by the client, so
          it cannot be known here until `task sync` has been run once. Filling
          it in afterwards costs nothing and stops a mesh peer from creating
          replicas at will — the ids land on the unit's command line, which is
          world-readable in the store, but an id is not a credential.
        '';
      };
    };

    config = {
      services.taskchampion-sync-server = {
        enable = true;
        inherit (cfg) port;
        allowClientIds = cfg.allowedClientIds;

        # Bound to the mesh rather than loopback: clients are other hosts, and
        # unlike most of what runs here this is reached directly rather than
        # through gaia. The netbird interface firewall is what limits reach.
        host = "0.0.0.0";

        # Pinned, not defaulted. Upstream ties this to stateVersion — it turns
        # itself on from 26.05 — and a DynamicUser with StateDirectory puts the
        # data in /var/lib/private/… behind a symlink. The persist entry below
        # would then bind-mount the symlink and every sync would start from
        # nothing after a reboot. Same trap microbin.nix and ollama.nix each
        # document; here it would arm itself on a stateVersion bump rather than
        # on anything anybody wrote.
        dynamicUser = false;
      };

      cosmos.system.impermanence.persist.directories = [
        "/var/lib/taskchampion-sync-server"
      ];
    };
  };
}
